Done 1st HW
Chepak-Semen/oop_lecture pull request #1
Opened 2020-12-25 13:20 UTC by Chepak-Semen

Не занеслися мені файли в gitignore. На наступний раз виправлю

2020-12-25 13:24 UTC, Chepak-Semen commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-ooP - Chepak Semen](https://trello.com/c/zxn8iJZq/8-hw1-oop-chepak-semen)

2020-12-26 15:50 UTC, yevhenii-khokhlov commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-OOP-Khokhlov Yevhenii](https://trello.com/c/RJnmLqST/11-hw1-oop-khokhlov-yevhenii)

2020-12-27 17:57 UTC, Masakinka commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-OOP-Borthikova Viktoriia](https://trello.com/c/CobK1m3J/14-hw1-oop-borthikova-viktoriia)

2020-12-27 18:34 UTC, volodymyrbekar commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-OOP-Bekar Volodymyr](https://trello.com/c/owlRj0Di/24-hw1-oop-bekar-volodymyr)

2020-12-27 19:00 UTC, volodymyrbekar commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-OOP-Bekar Volodymyr](https://trello.com/c/owlRj0Di/24-hw1-oop-bekar-volodymyr)

2020-12-27 20:00 UTC, RomansUA commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-OOP-Ravlyk Roman](https://trello.com/c/sUkeewst/16-hw1-oop-ravlyk-roman)

2020-12-27 21:26 UTC, ASIMER commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW1 - OOP - Illya Malyarenko](https://trello.com/c/Zlm6Zu4Q/26-hw1-oop-illya-malyarenko)

2020-12-27 21:27 UTC, aKondratyuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#1-OOP-Andrii Kondratyuk](https://trello.com/c/RPN3rf1U/25-hw1-oop-andrii-kondratyuk)

2020-12-29 13:29 UTC, dimigor requested changes

2020-12-29 13:29 UTC, dimigor commented on .idea/inspectionProfiles/profiles_settings.xml
> +</component>
do not commit files like this

2020-12-29 13:29 UTC, dimigor commented on Task3*.py
> +print(type(a))
Пиши виконавчий код в блоці if __name__=="__main__":

2020-12-29 13:29 UTC, dimigor commented on Task3*.py
> +print(type(a))
Також не забувай що в кожному файлику має бути останній рядок пустим

2020-12-29 13:29 UTC, dimigor commented on Task_2(Laptop).py
> +
а тут в тебе навпаки, забагато пустих рядків вкінці

2021-01-06 14:25 UTC, dimigor approved these changes

2021-01-06 14:25 UTC, dimigor commented on Task3*.py
> +    print(type(a))
не забувай за порожній рядок вкінці файлу

2021-01-10 17:55 UTC, merged