2 homework
Chepak-Semen/oop_lecture pull request #2
Opened 2021-01-10 18:20 UTC by Chepak-Semen

@dimigor or @Dimitri Gorbachevskii

2021-01-10 18:21 UTC, Chepak-Semen commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#2 - OOP_Practice - Chepak-Semen](https://trello.com/c/Uc1Zg5Z0/46-hw2-ooppractice-chepak-semen)

2021-01-12 14:49 UTC, dimigor requested changes

2021-01-12 14:49 UTC, dimigor commented on Homework_lec-2.py
> +
слідкуй за форматуванням
також документуй свій код
я не прошу щоб кожен метод був документований, але клас задокументуй

2021-01-12 14:49 UTC, dimigor commented on Homework_lec-2.py
> +        return f'__________________________________\n' \
форматування тут не дуже
Тут можеш просто зробити наступний вираз '20 * "_"' Що виведе 20 раз нижне пдчеркування

2021-01-12 14:49 UTC, dimigor commented on Homework_lec-2.py
> +            print(f'{self.name} can`t buy a house {home} because he need {home.cost - self.money}$ more')
можеш вивести тут якийсь ексепшин кастомний, а там де цей метод буде викликатись, обробляти його

2021-01-12 14:49 UTC, dimigor commented on Homework_lec-2.py
> +            print(f'Realtor {self.name} could not steal money in {self.client.name}')
так само ексепшин

2021-01-13 20:05 UTC, dimigor approved these changes

2021-01-14 12:13 UTC, merged